version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: aura_db
      POSTGRES_USER: aura_user
      POSTGRES_PASSWORD: your_strong_password
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: aura_user
      DB_PASSWORD: your_strong_password
      DB_NAME: aura_db
      DB_SSLMODE: disable
      JWT_SECRET: change_me_in_dev
      PORT: 8080
    ports:
      - "8081:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      PUBLIC_API_BASE: http://backend:8080
      PUBLIC_TRYIT_CHARTS: "1"
      PUBLIC_SITE_URL: http://localhost:3000
    ports:
      - "3000:3000"

volumes:
  db_data_dev: {}
