version: '3.8'
services:
  db:
    image: postgres:15-alpine # Use a specific, reliable version
    restart: always
    environment:
      POSTGRES_DB: aura_db
      POSTGRES_USER: aura_user
      POSTGRES_PASSWORD: your_strong_password # Change this!
    ports:
      - "5432:5432" # Connects your computer's port 5432 to the container's port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Saves data even if container stops

volumes:
  postgres_data: