global:
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: 'aura-backend'
    static_configs:
      - targets: ['backend:8080']
  - job_name: 'aura-backend-local'
    static_configs:
      - targets: ['host.docker.internal:8081']
