{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aura.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "aura.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secret.data }}
  {{ $k }}: "{{ $v }}"
{{- end }}
{{- end }}