apiVersion: v1
kind: Service
metadata:
  name: {{ include "aura.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "aura.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "aura.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
