name: ZAP Baseline Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start services (dev compose)
        run: |
          docker compose -f docker-compose.dev.yml up -d --build

      - name: Wait for frontend
        run: |
          for i in {1..60}; do
            if curl -sSf http://localhost:5173 >/dev/null; then exit 0; fi; sleep 5;
          done; exit 1

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:5173'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Stop services
        if: always()
        run: |
          docker compose -f docker-compose.dev.yml down -v
